### ISSUE TITLE
For BQ ver 7.0 - Please change the no of supported big-ip under management to 1000

### ISSUE THREAD

**Issue by adobre-f5** [f5devcentral/f5-agility-labs-big-iq#5]
for ver 7. 0, change here to say 1000 instead of 600:

https://clouddocs.f5.com/training/community/big-iq/html/class1/intro.html
F5® BIG-IQ:sup:® Centralized Management is a platform that you use as a tool to help you manage BIG-IP® devices and all of their services (such as LTM®, AFM®, ASM®, and so forth), from one location. BIG-IQ can manage **up to 600** (physical, virtual, or vCMP®) BIG-IP devices and handle licensing for up to 5,000 unmanaged devices.

**Comment by rjouhann** [comment]
We have removed this class and replaced with new Agility 2020 ADC class.
